Update

diff --git a/indentomatic b/indentomatic
--- a/indentomatic
+++ b/indentomatic
@@ -13,19 +13,19 @@ rm -f "$Tmp3"  >/dev/null 2>&1
 
 source ~/bash.library
 
-INDENT=""
-DELIM=" "
-BAR=""
-SPACE=""
-W=32
+filename="$1"
 
-while getopts "f:" arg
-do
-    case $arg in
-        f) 
-           indent_file "$OPTARG" 
-           ;;
-    esac
-done
-shift $(($OPTIND - 1))
+# Check if a filename is are provided
+if [ -z "$filename" ]; then
+  fecho "Usage: <filename> <filename>"
+  exit 1
+fi
+
+# Check if the files exist
+if [ ! -f "$filename" ]; then
+  fecho "Error: File '$filename' not found."
+  exit 1
+fi
+
+indent_file "$filename" 
 
